name: docker front end

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build container
      - uses: actions/checkout@v2
        run: |
          echo Building container,
          docker build -t jamescrosbie/front-end -f Dockerfile.dev .
          docker run -e CI=true jamescrosbie/front-end npm run test
